[alembic]
# Dossier contenant env.py et le sous-dossier versions/
script_location = %(here)s/migrations

# Ajoute le répertoire courant au sys.path — permet d'importer les modèles
prepend_sys_path = .

# Séparateur de chemins adapté à l'OS (\ sur Windows, / sur Linux)
path_separator = os

# URL de connexion sync — Alembic ne supporte pas asyncpg
sqlalchemy.url = postgresql+psycopg2://tts_user:tts_password@localhost:5432/tts_db


[post_write_hooks]
# Hooks désactivés — décommenter pour formater automatiquement les migrations avec black ou ruff


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

# Silencieux par défaut — passer à INFO pour voir les requêtes SQL générées
[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

# INFO — affiche les migrations appliquées dans le terminal
[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S